version: "3.8"

services:
  openapi-generator:
    command: generate -i /openapi/openapi.yaml -g openapi -o ./openapi
    image: openapitools/openapi-generator-cli
    volumes:
      - ./openapi:/openapi
