version: "3.8"

services:
  openapi-generator:
    command: generate -i /openapi/openapi.yaml -g openapi -o ./generated
    image: openapitools/openapi-generator-cli
    volumes:
      - ./openapi:/openapi
      - ./openapi.json:/generated/openapi.json # Copy only the api-doc json file
