openapi: '3.0.3'

info:
  title: Maistissa backend
  version: '1.1.0'

servers:
  - url: http://localhost:8082/api

tags:
- name: reviews-crud
  description: CRUD operations for reviews.
- name: wines-crud
  description: CRUD operations for wines.
- name: wines-info
  description: Operations for finding information regarding wines.
- name: wines-search
  description: Wine search functionality.

paths:
  # Reviews CRUD operations
  /reviews:
    $ref: ./reviews/paths-crud.yaml#/Reviews
  /reviews/{id}:
    $ref: ./reviews/paths-crud.yaml#/Review
  /reviews/{wineId}:
    $ref: ./reviews/paths-crud.yaml#/AddReview
  /reviews/{id}/editable:
    $ref: ./reviews/paths-crud.yaml#/ReviewEditable

  # Wines CRUD operations
  /wines:
    $ref: ./wines/paths-crud.yaml#/Wines
  /wines/{id}:
    $ref: ./wines/paths-crud.yaml#/Wine
  /wines/{id}/editable:
    $ref: ./wines/paths-crud.yaml#/WineEditable

  # Wines info operations
  /wines/count:
    $ref: ./wines/paths-info.yaml#/WinesCount
  /wines/countries:
    $ref: ./wines/paths-info.yaml#/WinesCountries
  /wines/descriptions:
    $ref: ./wines/paths-info.yaml#/WinesDescriptions
  /wines/food-pairings:
    $ref: ./wines/paths-info.yaml#/WinesFoodPairings
  /wines/validate:
    $ref: ./wines/paths-info.yaml#/ValidateName

  # Wine search
  /wines/search:
    $ref: ./wines/paths-search.yaml#/WineSearch
  
components:
  schemas:
    ErrorBody:
      $ref: ./common/errors.yaml#/ErrorBody
    Review:
      $ref: ./reviews/schemas.yaml#/Review
    Wine:
      $ref: ./wines/schemas.yaml#/Wine
