# Builds the openapi.json schema by using Docker Compose and pushes it to GitHub.
name: Master branch workflow

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build openapi.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up
      - run: cat openapi.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically update openapi.json
          # commit_options: '--no-verify --signoff'
          file_pattern: openapi.json
